import { notFound } from "next/navigation";
import { requireField } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { ProductImage } from "@/components/ProductImage";
import { formatCurrency } from "@/lib/format";
import { registerStorePaymentAction, updateStoreInternalNoteAction } from "@/lib/store-actions";

export const dynamic = "force-dynamic";

export default async function FieldStorePage({ params }: { params: Promise<{ id: string }> }) {
  await requireField(); const { id } = await params;
  const store = await prisma.store.findUnique({ where: { id:Number(id) }, include: { shelves:true, routeLine:true, orders:{ include:{items:true}, orderBy:{createdAt:"desc"}, take:8 }, financeEntries:{ where:{type:"INCOME"}, orderBy:{entryDate:"desc"}, take:8 } } });
  if (!store) notFound();
  return <div className="container-page max-w-5xl"><div className="grid gap-6 md:grid-cols-[260px_1fr]"><ProductImage src={store.exteriorImage} alt={store.name} className="aspect-[4/3] w-full rounded-2xl"/><div><p className="eyebrow">Карточка магазина</p><h1 className="mt-2 text-3xl font-semibold">{store.name}</h1><p className="mt-2 text-zinc-500">{store.address}</p><div className="mt-4 flex flex-wrap gap-2"><span className={`rounded-full px-3 py-1.5 text-sm font-semibold ${store.debt > 0 ? "bg-rose-100 text-rose-800" : "bg-emerald-100 text-emerald-800"}`}>Долг: {formatCurrency(store.debt)}</span>{store.routeLine && <span className="admin-chip">{store.routeLine.title}</span>}</div><div className="mt-5 flex flex-wrap gap-2"><a className="button-primary" href={`/field/stores/${store.id}/order`}>Оформить продажу</a>{store.phone&&<a className="button-secondary" href={`tel:${store.phone}`}>Позвонить</a>}{store.latitude&&store.longitude&&<a className="button-secondary" target="_blank" rel="noreferrer" href={`https://yandex.ru/maps/?rtext=~${store.latitude},${store.longitude}&rtt=auto`}>Открыть маршрут</a>}</div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="surface-card p-4"><span className="text-xs text-zinc-500">Полка</span><strong className="mt-1 block">{store.shelves.map(s=>s.code).join(", ")||"Не установлена"}</strong></div><div className="surface-card p-4"><span className="text-xs text-zinc-500">Контакт</span><strong className="mt-1 block">{store.contactName||store.phone||"—"}</strong></div></div></div></div>

    <div className="mt-8 grid gap-6 lg:grid-cols-2">
      {store.debt > 0 ? <form action={registerStorePaymentAction} className="surface-card p-5"><input type="hidden" name="storeId" value={store.id}/><h2 className="font-semibold">Принять оплату от магазина</h2><p className="mt-1 text-sm text-zinc-500">Текущий долг: {formatCurrency(store.debt)}. Сумма попадёт в поступления и уменьшит долг.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label><span className="field-label">Сумма</span><input className="input" name="amount" type="number" min="0.01" max={store.debt} step="0.01" required /></label><label><span className="field-label">Способ</span><select className="input" name="paymentMethod"><option>Наличные</option><option>Перевод</option><option>Безнал</option><option>Другое</option></select></label></div><label className="mt-4 block"><span className="field-label">Комментарий к оплате</span><input className="input" name="note" placeholder="Например: оплата за прошлую поставку" /></label><button className="button-primary mt-4">Записать оплату</button></form> : <div className="surface-card p-5"><h2 className="font-semibold">Задолженности нет</h2><p className="mt-2 text-sm text-zinc-500">Оплату текущей продажи фиксируйте при оформлении продажи.</p></div>}
      <form action={updateStoreInternalNoteAction} className="surface-card p-5"><input type="hidden" name="storeId" value={store.id}/><h2 className="font-semibold">Примечание к магазину</h2><p className="mt-1 text-sm text-zinc-500">Старый текст можно полностью стереть и сохранить новый.</p><textarea className="input mt-4 min-h-28" name="notes" defaultValue={store.notes ?? ""} placeholder="Заезд после 14:00, звонить заранее…"/><button className="button-secondary mt-4">Сохранить примечание</button></form>
    </div>

    <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="surface-card p-5"><h2 className="font-semibold">История заказов</h2><div className="mt-4 divide-y divide-zinc-100">{store.orders.map(o=><div key={o.id} className="py-4"><div className="flex justify-between"><strong>Заказ №{o.id}</strong><span className="text-sm text-zinc-500">{o.status}</span></div><p className="mt-2 text-sm text-zinc-600">{o.items.map(i=>`${i.productName} — ${i.quantity}`).join("; ")}</p><div className="mt-2 text-sm font-semibold">{formatCurrency(o.total)} · {o.paymentStatus}</div></div>)}{store.orders.length===0&&<p className="py-5 text-zinc-500">Заказов нет.</p>}</div></section><section className="surface-card p-5"><h2 className="font-semibold">Последние оплаты</h2><div className="mt-4 divide-y divide-zinc-100">{store.financeEntries.map(e=><div key={e.id} className="flex items-start justify-between gap-4 py-3"><div><strong className="text-sm">{e.category}</strong><p className="mt-1 text-xs text-zinc-500">{new Intl.DateTimeFormat("ru-RU").format(e.entryDate)} · {e.paymentMethod ?? "—"}</p></div><strong className="text-emerald-700">{formatCurrency(e.amount)}</strong></div>)}{store.financeEntries.length===0&&<p className="py-5 text-zinc-500">Оплат пока нет.</p>}</div></section></div>
  </div>;
}
